//SYSTEM
export const SET_CURRENT_THEME = "SET_CURRENT_THEME";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const GET_USERS_BY_NAME = "GET_USERS_BY_NAME";

//ROOM
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_MESSAGE="GET_MESSAGE";








