//SYSTEM
export const SET_CURRENT_THEME = "SET_CURRENT_THEME";

//USER
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const GET_USERS_BY_NAME = "GET_USERS_BY_NAME";
export const SET_UPDATING_DISPLAY_NAME = "SET_UPDATING_DISPLAY_NAME";
export const UNSET_UPDATING_DISPLAY_NAME = "UNSET_UPDATING_DISPLAY_NAME";
export const SET_UPDATING_STATUS = "SET_UPDATING_STATUS";
export const UNSET_UPDATING_STATUS = "UNSET_UPDATING_STATUS";
export const SET_UPDATING_PHOTO = "SET_UPDATING_PHOTO";
export const UNSET_UPDATING_PHOTO = "UNSET_UPDATING_PHOTO";
export const ADD_CHAT_TO_ROOM = "ADD_CHAT_TO_ROOM";
export const SET_SIGN_UP_ERRORS = "SET_SIGN_UP_ERRORS";
export const CLEAR_SIGN_UP_ERRORS = "CLEAR_SIGN_UP_ERRORS";
export const SET_SIGN_IN_ERRORS = "SET_SIGN_IN_ERRORS";
export const CLEAR_SIGN_IN_ERRORS = "CLEAR_SIGN_IN_ERRORS";


//ROOM
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";
